// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package org.example.proto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();
}
